### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by ishara3** [strangerstudios/pmpro-series#11]
Hi, 
Have just installed paid memberships pro and pmpro series on my wordpress site. Have been able to create a membership level, create a series, add posts, register for membership level.. But series is not added a link to my available content to my Membership Account page, nor does it send any emails to me to say new content is available.  Even though it now says on the Series page that I am on day three of membership and have access to three pages. 
When I look at the class.pmproseries.php code, the SendEmail function does not appear to have any content.  Is this a bug?  
thanks,
Ishara

**Comment by dparker1005** [comment]
Hi @ishara3, the content of the PMPro Series emails should be loaded from the `/email/new-content.html` template here: https://github.com/strangerstudios/pmpro-series/blob/dev/email/new_content.html

And here is where we actually add that template to the body of the email: https://github.com/strangerstudios/pmpro-series/blob/4092d7794acb7de3767c1e25b058789b72e3c8e3/classes/class.pmproseries.php#L255

As this issue is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
