### ISSUE TITLE
Series page is LIVE but gives 404 when loaded

### ISSUE THREAD

**Issue by webdevman** [strangerstudios/pmpro-series#12]
You can see that the page is live in the first image.
A post is added and working fine (2nd image - visible after 0 days)

But the page which lists the series does not load (3rd image).

![page1](https://cloud.githubusercontent.com/assets/7079344/2535366/6e31e3ae-b58d-11e3-9b4c-7a99cd21c9a0.jpg)
![error2](https://cloud.githubusercontent.com/assets/7079344/2535368/6e532f96-b58d-11e3-838a-0daf9cf400de.jpg)
![error1](https://cloud.githubusercontent.com/assets/7079344/2535367/6e52446e-b58d-11e3-9c83-a1ddd1b70f9b.jpg)

Why is the permalink to the page not working?

Thanks in advance,
-Nick

**Comment by dparker1005** [comment]
We are currently cleaning up this repository. As this issue is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
