### ISSUE TITLE
membership days not calculated correctly

### ISSUE THREAD

**Issue by kayno** [strangerstudios/pmpro-series#2]
In the last couple of days I installed the PMP plugin and this pmpro-series plugin. I created a series and added some dripped content.

I then gave the admin user a membership by editing the account's profile, and when I look at the series, I see **You are on day 15826 of your membership.**.

15826 days is 43 odd years, taking us back to 1970, the unix epoch...

I checked the "Membership report" page in the PMP settings, and admin is listed with a join date of **04/30/2013**.

Is this a bug in pmpro-series or something else?

Thanks
Kayne

**Comment by dparker1005** [comment]
There have been updates in core PMPro to reduce the number of instances where the membership day count is off. Particularly, this commit to core PMPro should have resolved the `1970` issue which this ticket is about:
https://github.com/strangerstudios/paid-memberships-pro/commit/ed20a56a90def956ad48d79bdc57aeff29c879be

As this issue is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
