### ISSUE TITLE
User informed that content will available on wrong date

### ISSUE THREAD

**Issue by agrolsy** [strangerstudios/pmpro-series#25]
The user was informed that the content would be available on a date before it actually would be made available.

membership_startdate = 2014-08-15
values for today (2014-10-04)
member days: 50 day 56: days left 6
Read
You will gain access on 2014-10-04 (today)

when it should be
You will gain access on 2014-10-10 (6 days from now, since it 6 days left)

adding intval to line 216, changing it from
$member_days = pmpro_getMemberDays($current_user->ID);
to
$member_days = intval(pmpro_getMemberDays($current_user->ID));

and moving one bracket, ending get_option after "date_format", on line 218, changing it  from
$date = date(get_option("date_format", strtotime("+ $days_left Days", current_time("timestamp"))));

to
$date = date(get_option("date_format"), strtotime("+ $days_left Days", current_time("timestamp")));

solved that for me

**Comment by dparker1005** [comment]
The `$date` line change now appears to be correct in recent versions of PMPro Series: https://github.com/strangerstudios/pmpro-series/blob/4092d7794acb7de3767c1e25b058789b72e3c8e3/classes/class.pmproseries.php#L393

As this issue is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
