### ISSUE TITLE
Membership Days not advancing?

### ISSUE THREAD

**Issue by chrisio1** [strangerstudios/pmpro-series#26]
Hi.

We have this plugin installed and on the face of it, its working just fine.  The problem is the days since joining don't seem to be advancing therefore the series is not advancing.

Can you offer any suggestions?

Thanks
Chris

**Comment by dparker1005** [comment]
Hi @chrisio1,

We calculate the number of days that a user has been a member on yours site by calculating the number of days since their membership start date. Ensuring that date is being set correctly for new members on your site should be the first step in debugging why membership days are not advancing. It may also be worth checking that caching is not interfering with the PMPro Series functionality.

As this question is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
