### ISSUE TITLE
Keeps sending emails about new content after completion

### ISSUE THREAD

**Issue by mijak99** [strangerstudios/pmpro-series#28]
Hi, 

I have setup a series with only 2 entries, one for day 0 and one for day 1. 
Day 1, I get the "new content" email just fine. 

However, on day 2, 3, etc.. I keep getting a "New content is available" email every day, although the series is complete. 

I suspect the pmpros_check_for_new_content()  should be adjusted, but any input on how to do this is welcome.

**Comment by dparker1005** [comment]
Hello,

PMPro Series uses the `pmpros_notified` usermeta field to track which series posts users have already been notified about and to prevent users from being notified about the same series posts multiple times:
https://github.com/strangerstudios/pmpro-series/blob/d64630adee64257900065f79c8893bba66b54206/scheduled/crons.php#L35-L38

The next step that I would take in debugging this issue would be to ensure that usermeta fields is being set correctly, but as this issue is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
