### ISSUE TITLE
PMPro Series warning issue

### ISSUE THREAD

**Issue by moneysharp** [strangerstudios/pmpro-series#8]
I am using Paid Memberships Pro version 1.7.4
I added PMPro Series Version .2 for Drip Content.
I configured the pages for the drip content.
Wordpress version 3.7.1

When I access the pages in the drip content I am able to view the page if I have access based on the number of day I am a member.
Day 0 gives me page 1 access, day 30 gives me page 2 access and so on.

Everything seems to be working properly except that I get the following error at the top of the page

Warning: Invalid argument supplied for foreach() in /home/content/44/11963544/html/wp-content/plugins/pmpro-series/pmpro-series.php on line 141

I deleted and reinstalled the PMPro series add-on to see if this resoveld the issue no luck. I even deleted the series I had created and created it over to see if that resolved the issue, still no luck.

**Comment by dparker1005** [comment]
This warning should have been resolved in the PMPro Series v0.2.1 release:
https://github.com/strangerstudios/pmpro-series/commit/690fbb32aecdeb245672edf078c682d9ac1036f2

As this issue is several years old and there have not been recent reports of this behavior, we are going to close this issue. If you are still experiencing this error on your site, please feel free to open a new issue in this Add On's GitHub repo and link back to this issue, or [open a new ticket in our Support Forums](https://www.paidmembershipspro.com/new-topic/) and we can help you there.
